// 토미쌤 잉글리시 - 너서리 픽처북 추천 리스트 & Read Aloud 데이터
// 각 책: title(제목), author(작가), desc(설명), url(유튜브 read aloud, 없으면 null), koUrl(한국어 리드얼라우드, 있는 경우만)

const BOOKS = [
  { title: "I Just Ate My Friend", author: "Heidi McKinnon", desc: "친구를 잡아먹어버린(?) 귀여운 괴물이 새 친구를 찾아나서는 유머러스한 그림책. 반복 문장 구조.", url: "https://www.youtube.com/watch?v=VYmR2L1QImo" },
  { title: "Five Little Monkeys Jumping on the Bed", author: "Eileen Christelow", desc: "클래식 카운팅 동요책. 리듬감 있는 반복 문장으로 시작하기 좋음.", url: "https://www.youtube.com/watch?v=Xk6MP5sSsKo" },
  { title: "Can I Play Too?", author: "Mo Willems (Elephant & Piggie)", desc: "제럴드와 피기, 뱀 친구의 놀이 이야기. 쉬운 대화체 문장.", url: "https://www.youtube.com/watch?v=8vbr81Vf9Hc" },
  { title: "A Cat and a Dog", author: "Claire Masurel", desc: "사이 나쁜 고양이와 개가 서로 도와주며 친구가 되는 이야기. 초간단 문장.", url: "https://www.youtube.com/watch?v=CAqqe7tPyZI" },
  { title: "Good Night, Gorilla", author: "Peggy Rathmann", desc: "거의 무자언에 가까운 클래식 베드타임 스토리. 반복 프레이즈 \"Good night, ___\".", url: "https://www.youtube.com/watch?v=xJR8dVTYWK0" },
  { title: "Ketchup on Your Cornflakes?", author: "Nick Sharratt", desc: "\"Do you like ___ on your ___?\" 패턴으로 음식 어휘와 Yes/No 질문 구조 연습.", url: "https://www.youtube.com/watch?v=XQyWuQi476E" },
  { title: "Tap the Magic Tree", author: "Christie Matheson", desc: "나무를 두드리고 흔들며(인터랙티브) 계절 변화를 배우는 그림책.", url: "https://www.youtube.com/watch?v=bVz7pNigjYM" },
  { title: "A Funny Man", author: "정확한 출판 정보 확인 필요", desc: "정식 read aloud 영상을 찾지 못했습니다. 표지·저자 정보를 알려주시면 다시 찾아볼게요.", url: null },
  { title: "Ness the Nurse", author: "Nick Sharratt", desc: "반창고를 세는 라이밍 카운팅 보드북. Scholastic Storyboard 시리즈.", url: "https://www.youtube.com/watch?v=bNfH1UFvMvU" },
  { title: "Boo Who?", author: "Sally Symes / Nick Sharratt", desc: "공룡 캐릭터들의 까꿍 놀이 라이밍 보드북. 정식 read aloud 영상은 찾지 못했습니다.", url: null },
  { title: "Hooray for Hat!", author: "Brian Won", desc: "기분이 안 좋은 코끼리가 모자를 선물받고 친구들과 나누는 이야기. 반복 프레이즈 \"Hooray for hat!\"", url: "https://www.youtube.com/watch?v=dGb9eGBo9mk" },
  { title: "Skeleton Hiccups", author: "Margery Cuyler", desc: "딸꾹질하는 해골 이야기. 짧고 리드미컬한 할로윈 그림책.", url: "https://www.youtube.com/watch?v=Br8wqAFfC4g" },
  { title: "Don't Put Your Finger in the Jelly, Nelly!", author: "Nick Sharratt", desc: "구멍에 손가락을 넣어 숨은 동물을 찾는 인터랙티브 다이컷 그림책.", url: "https://www.youtube.com/watch?v=bvl_mhANWNw", koUrl: "https://www.youtube.com/watch?v=ALdTENv77I4" },
  { title: "Go Away, Big Green Monster!", author: "Ed Emberley", desc: "다이컷으로 몬스터 얼굴을 만들었다 없애는 클래식 그림책. 두려움 극복 테마.", url: "https://www.youtube.com/watch?v=LuHshs0hhcM" },
  { title: "Ten Fat Sausages", author: "전통 동요 기반 (Child's Play 시리즈)", desc: "프라이팬 속 소시지가 하나씩 사라지는 카운트다운 동요책.", url: "https://www.youtube.com/watch?v=h-npsK-SIG0" },
  { title: "Love the World", author: "Todd Parr", desc: "자기 자신과 세상을 사랑하자는 라이밍 그림책. Todd Parr 특유의 밝은 색감.", url: "https://www.youtube.com/watch?v=mkM7-daV0M8" },
  { title: "Let's Play Monsters!", author: "Lucy Cousins", desc: "가브리엘이 가족들에게 몬스터 역할극을 시키며 노는 반복 구조 그림책.", url: "https://www.youtube.com/watch?v=zxXptxBlTS4" },
  { title: "A Hole in the Bottom of the Sea", author: "Jessica Law (Barefoot Books)", desc: "전통 동요를 기반으로 한 누적형(cumulative) 바다 생물 노래책.", url: "https://www.youtube.com/watch?v=R1Qn2bcZRTo" },
  { title: "What Am I?", author: "N.N. Charles (그림 Leo & Diane Dillon)", desc: "도형 구멍으로 과일을 맞추는 색깔·모양 개념북. 정식 read aloud 영상은 찾지 못했습니다.", url: null },
  { title: "Duck, Duck, Goose!", author: "Tad Hills", desc: "오리 둘과 거위의 우정에 새 오리 친구가 끼어들며 생기는 갈등과 화해.", url: "https://www.youtube.com/watch?v=sHY-OOkA7JI" },
  { title: "Monster, Monster", author: "Melanie Walsh", desc: "집 안에 숨은 몬스터를 플랩(들춰보기)으로 찾는 인터랙티브 그림책.", url: "https://www.youtube.com/watch?v=UkLlAwoPzWI" },
  { title: "Feathers and Hair, What Animals Wear", author: "Jennifer Ward", desc: "동물들이 \"입고 있는\" 깃털/털/가시 등을 라이밍으로 소개하는 논픽션 그림책.", url: "https://www.youtube.com/watch?v=a2BG0doPGf8" },
  { title: "Head, Shoulders, Knees and Toes", author: "Annie Kubler (보드북)", desc: "클래식 동요를 그림으로 따라 부르는 보드북.", url: "https://www.youtube.com/watch?v=OslgnQl5fII" },
  { title: "Brown Bear, Brown Bear, What Do You See?", author: "Bill Martin Jr. / Eric Carle", desc: "색깔 동물이 등장하는 반복 문장 클래식.", url: "https://www.youtube.com/watch?v=_b7G5ji0Gc8" },
  { title: "Chicka Chicka Boom Boom", author: "Bill Martin Jr. & John Archambault", desc: "알파벳들이 코코넛 나무를 오르는 리드미컬한 알파벳북.", url: "https://www.youtube.com/watch?v=eHApk4USlGw" },
  { title: "1-2-3 Peas", author: "Keith Baker", desc: "완두콩 캐릭터들이 활동하며 1~100까지 소개하는 숫자책.", url: "https://www.youtube.com/watch?v=L58exhbQTbw" },
  { title: "Don't Push the Button!", author: "Bill Cotter", desc: "몬스터 래리가 버튼을 누르지 말라고 하지만 결국 누르게 되는 인터랙티브 그림책.", url: "https://www.youtube.com/watch?v=Ks23HDEm830" },
  { title: "Run, Mouse, Run!", author: "Petr Horacek", desc: "쥐가 집 안을 도망다니는 다이컷 보드북. 정식 read aloud 영상은 찾지 못했습니다.", url: null },
  { title: "Driving My Tractor", author: "Jan Dobbins", desc: "트랙터를 몰고 다니며 동물을 태우는 카운팅 송북.", url: "https://www.youtube.com/watch?v=Y5hMpdvblsY" },
  { title: "Color Me Happy", author: "정확한 출판 정보 확인 필요", desc: "색깔로 감정을 표현하는 고양이 그림책으로 추정되나, 정확한 출판사/작가를 특정하지 못했습니다.", url: null },
  { title: "Today is Monday", author: "Eric Carle", desc: "요일별 음식이 등장하는 전통 동요 기반 그림책.", url: "https://www.youtube.com/watch?v=E5adm2vxD04" },
  { title: "Faster, Faster! Nice and Slow", author: "Nick Sharratt & Sue Heap", desc: "반의어(빠름/느림 등)를 소개하는 그림책. 정식 read aloud 영상은 찾지 못했습니다.", url: null },
  { title: "From Head to Toe", author: "Eric Carle", desc: "동물들의 움직임을 따라하는 인터랙티브 그림책.", url: "https://www.youtube.com/watch?v=a-GcxJW8wVw" },
  { title: "Hippo Has a Hat", author: "Julia Donaldson / Nick Sharratt", desc: "옷가게에서 동물들이 옷을 고르는 라이밍 그림책.", url: "https://www.youtube.com/watch?v=nzhgxnSpn2I" },
  { title: "Hop Jump", author: "Ellen Stoll Walsh", desc: "깡충깡충 뛰기만 하던 개구리 벳시가 춤을 발견하는 이야기.", url: "https://www.youtube.com/watch?v=nZx_OJcfvP4" },
  { title: "One of These Is Not Like the Others", author: "Barney Saltzberg", desc: "다름을 인정하고 축하하는 컨셉북.", url: "https://www.youtube.com/watch?v=T21Aqpe4iLM" },
  { title: "Big, Bigger, Biggest", author: "크기 비교 컨셉 보드북", desc: "크고 작음을 비교하며 배우는 컨셉북.", url: "https://www.youtube.com/watch?v=2PWxyJ72YGg" },
  { title: "Yes Day!", author: "Amy Krouse Rosenthal / Tom Lichtenheld", desc: "뭐든지 \"Yes\"라고 답해주는 특별한 하루를 그린 이야기.", url: "https://www.youtube.com/watch?v=ee8dj8CYcUo" },
];
